In [3]:
import torch
import numpy as np
def loss_v2_plus_plus():
    rewards = torch.tensor(np.array([[1,2],[4,3],[5,6],[8,7]],dtype=np.float32), requires_grad=True)
    print(rewards)
    print(rewards[:,0])
    sub_first_rewards = rewards-rewards[:,0][:,None]
    print(sub_first_rewards)
    loss_value = torch.sum(sub_first_rewards.exp(), -1).log().mean()
    return loss_value

print(loss_v2_plus_plus())

tensor([[1., 2.],
        [4., 3.],
        [5., 6.],
        [8., 7.]], requires_grad=True)
tensor([1., 4., 5., 8.], grad_fn=<SelectBackward0>)
tensor([[ 0.,  1.],
        [ 0., -1.],
        [ 0.,  1.],
        [ 0., -1.]], grad_fn=<SubBackward0>)
tensor(0.8133, grad_fn=<MeanBackward0>)
